Hello World and Print in the Python

In [1]:
print("Hello World")

Hello World


In [2]:
print(1)

1


In [3]:
print(1.0)

1.0


In [4]:
print(0.0999)

0.0999


**Basic Arithmatic**

In [5]:
1 + 5

6

In [6]:
5/2

2.5

In [7]:
2/5

0.4

In [8]:
2*2

4

In [9]:
3*3

9

In [10]:
# Power of x here 3^3 = 27
3**3

27

**Start with Basic Library NumPy:** http://www.numpy.org/

In [11]:
#Open the library
# Here We write thr np, So, we want to write np istead of numpy
import numpy as np

In [12]:
# Create a Numpy matrix in order
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

In [13]:
# Check Size of the array
# It returns Row x Column
a.shape

(4, 5)

**ndarray.ndim**

the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

In [14]:
a.ndim

2

Create 1 Dimensional Array

In [15]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

Create a two dimensional array

In [16]:
b = np.array([[6, 7, 8],[5,6,7]])
b

array([[6, 7, 8],
       [5, 6, 7]])

In [17]:
b.shape

(2, 3)

In [18]:
#Type of the Object
type(b)

numpy.ndarray

In [19]:
# Float
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [20]:
# Complex
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [21]:
#create a zero matrix
d = np.zeros((3,4))
d

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [22]:
e = np.ones((3,4))
e

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [23]:
# get the array with min and max with step of 5
f = np.arange( 10, 30, 5 )
f

array([10, 15, 20, 25])

In [24]:
g = np.arange( 0, 2, 0.3 )
g

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [25]:
# Array of 9 elements with 0 and 2
h = np.linspace( 0, 2, 9 )
h

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [26]:
# Random number generator in 
np.random.rand(3,2)

array([[ 0.1555602 ,  0.95254674],
       [ 0.7340185 ,  0.51013918],
       [ 0.32133029,  0.24549227]])

In [27]:
j = np.random.randint(5, size=(2, 4))
j

array([[4, 2, 4, 2],
       [3, 3, 2, 2]])

In [28]:
np.random.random((2,2))

array([[ 0.80275301,  0.72023384],
       [ 0.12544362,  0.71232783]])

# Generate Unique Random Variable

In [29]:
import random
random.sample(range(1, 100), 3)

[19, 21, 3]

# Import PI= 3.14 directly


In [30]:
from numpy import pi

In [31]:
pi

3.141592653589793

# Basic Operation

In [32]:
a = np.array( [20,30,40,50] )
print(a)
b = np.arange( 4 )
print(b)

[20 30 40 50]
[0 1 2 3]


In [33]:
c = a-b
c

array([20, 29, 38, 47])

In [34]:
#Logical Statement
c<29

array([ True, False, False, False], dtype=bool)

In [35]:
# Minimum Value
c.min()


20

In [36]:
# Maximum Value
c.max()

47

In [37]:
b = np.arange(12).reshape(3,4)
b.sum(axis=0)  # Sum of each column
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Plot the Data with matplotlib

In [38]:
# Plot the Data
import numpy as np
import matplotlib.pyplot as plt


In [40]:
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()

In [41]:

plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.axis([0, 6, 0, 20])
plt.show()

In [42]:
t = np.arange(0., 5., 0.2)

# red dashes, blue squares and green triangles
plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^')
plt.show()

In [43]:
def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure(1)
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')
plt.show()

In [49]:
mu, sigma = 100, 5
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, normed=1, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.grid(True)
plt.show()

In [50]:
mu, sigma = 100, 25
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, normed=1, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.grid(True)
plt.show()

In [51]:
ax = plt.subplot(111)

t = np.arange(0.0, 5.0, 0.01)
s = np.cos(2*np.pi*t)
line, = plt.plot(t, s, lw=2)

plt.annotate('local max', xy=(2, 1), xytext=(3, 1.5),
            arrowprops=dict(facecolor='black', shrink=0.05),
            )

plt.ylim(-2,2)
plt.show()

In [52]:
y = np.random.normal(loc=0.5, scale=0.4, size=1000)
y = y[(y > 0) & (y < 1)]
y.sort()
x = np.arange(len(y))

# plot with various axes scales
plt.figure(1)

# linear
plt.subplot(221)
plt.plot(x, y)
plt.yscale('linear')
plt.title('linear')
plt.grid(True)


# log
plt.subplot(222)
plt.plot(x, y)
plt.yscale('log')
plt.title('log')
plt.grid(True)


# symmetric log
plt.subplot(223)
plt.plot(x, y - y.mean())
plt.yscale('symlog', linthreshy=0.05)
plt.title('symlog')
plt.grid(True)

# logit
plt.subplot(224)
plt.plot(x, y)
plt.yscale('logit')
plt.title('logit')
plt.grid(True)

plt.show()